[package]
name = "cohere2-burn"
version = "0.1.0"
edition = "2021"
authors = ["Jozef Lumaj"]
description = "Cohere 2 Architecture"

[dependencies]
burn = {version = "0.21.0", default-features = false, features = ["std", "vulkan"] }
tokenizers = {version = "0.23.1"}
askama = {version="0.16.0"}
serde = {version = "1", default-features = false}
serde_json = {version="1"}
ahash = {version="0.8.12"}
#itertools = {version = "0.14", default-features = false}
